database:
  container_name: "postgres"
  container_type: "database"

paths:
  # путь к исходным sql файлам
  source_sql_files: "C:\\Users\\Andrey_Potapov\\YandexDisk\\Practice\\Programs\\D&A.Grow\\materials\\D&A.Grow scripts\\work_item\\BL-156\\pg_dp_deploy_output\\ScoreManager_DB"
  # путь к файлу с результатами работы sql_processor
  output_json: "output-files.json"
  # путь к папке с результатами работы программы
  output_folder: "C:\Temp\dataflow-doc-generator\output"
  # путь к папке с примером результатов работы программы
  example_output_folder: "C:\repos\personal\dataflow-doc-generator\output"

visualization:
  height: "750px"
  width: "100%"
  colors:
    table: "lightblue"
    default: "lightgreen" 